### ISSUE TITLE
problems I met when I was running the code for solubility

### ISSUE THREAD

**Issue by lacendre** [baldassarreFe/graph-network-explainability#1]
Hi! I met some problems when I was running the predict part of code for solubility. I'm wondering how can I find the datasets for this part, because it seems that some ".yaml" files are absent?

**Comment by baldassarreFe** [comment]
Hi, can you be more specific about the problem you are encountering? If you're getting an error, can you paste the message?

The dataset for the solubility task is in the [`data`](https://github.com/baldassarreFe/graph-network-explainability/tree/master/data) folder as single csv file. 

Yaml files are used for configuration, [`config/solubility/train.yaml`](https://github.com/baldassarreFe/graph-network-explainability/blob/master/config/solubility/train.yaml) should be self-contained and can be run with:
```bash
python -m solubility.train --experiment ../config/solubility/train.yaml
```

**Comment by davidwhealey** [comment]
Hi, I'm encountering the same thing, specifically when running

```python -m solubility.train \
   --experiment ../config/solubility/train.yaml \
   --model ../config/solubility/minimal.yaml```

I encounter the error
```FileNotFoundError: [Errno 2] No such file or directory: '../config/solubility/minimal.yaml'```

**Comment by baldassarreFe** [comment]
Hi David, as I suggested in the previous answer, the config file [config/solubility/train.yaml](https://github.com/baldassarreFe/graph-network-explainability/blob/498a50956147711f55c3a6a8175db88a5182f946/config/solubility/train.yaml) is self-contained, i.e. a separate file with the definition of the model is not needed.

You should be fine with running this from the main repo folder:
```bash
python -m solubility.train --experiment ./config/solubility/train.yaml
```

I'll update the readme so no one incurs in the same problem ;)
